---
# tasks file for apache2 server

# install apache2 server
- name: install apache2 software
  become: yes
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - apache2

# adding apache to the startup process
- name: add apache2 to the startup process
  become: yes
  shell: update-rc.d apache2 defaults

# start apache2 service
- name: apache2 start up
  become: yes
  service:
    name: apache2
    state: started
